{{- range .Values.tunnels }}
{{- if .enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ktunnels.fullname" $ }}-{{ .name }}
  labels:
    {{- include "ktunnels.labels" $ | nindent 4 }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ktunnels.selectorLabels" $ | nindent 6 }}
      run: {{ include "ktunnels.fullname" $ }}-{{ .name }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ktunnels.labels" $ | nindent 8 }}
        run: {{ include "ktunnels.fullname" $ }}-{{ .name }}
	{{- with $.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ktunnels.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: gfleury/ssh-client
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ["ssh"]
          args:
            - "-i"
            - "/etc/sshkeys/ssh_key"
            - "-o"
            - "UserKnownHostsFile=/dev/null"
            - "-o"
            - "StrictHostKeyChecking=no"
            - "-N"
            - "-L"
            - "0.0.0.0:{{ .port }}:{{ .serviceHost }}:{{ .servicePort }}"
            - "{{ .sshUser }}@{{ .sshHost }}"
            - "-p"
            - "{{ .sshPort | default "22" }}"
          ports:
            - name: http
              containerPort: {{ .port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe: 
            tcpSocket:
              port: {{ .port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
            - name: sshkey-volume
              mountPath: /etc/sshkeys/ssh_key
              subPath: sshKey
      volumes:
        - name: sshkey-volume
          secret:
            secretName: {{ include "ktunnels.fullname" $ }}-{{ .name }}
            defaultMode: 256
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
