{{- range .Values.tunnels }}
{{- if .enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ktunnels.fullname" $ }}-{{ .name }}
  labels:
  {{- include "ktunnels.labels" $ | nindent 4 }}
data:
  sshKey: {{ .sshKey | b64enc }}
{{- end }}
{{- end }}