{{- range .Values.tunnels }}
{{- if .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ktunnels.fullname" $ }}-{{ .name }}
  labels:
    {{- include "ktunnels.labels" $ | nindent 4 }}
    run: {{ include "ktunnels.fullname" $ }}-{{ .name }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ .servicePort }}
      protocol: TCP
  selector:
    {{- include "ktunnels.selectorLabels" $ | nindent 4 }}
    run: {{ include "ktunnels.fullname" $ }}-{{ .name }}
{{- end }}
{{- end }}